### ISSUE TITLE
Illegal characters found in URL  Exited with code exit status 3

### ISSUE THREAD

**Issue by gnikolov5** [CircleCI-Public/jq-orb#35]
Hello,

Most likely since the release of the new version of jq 1.7.1 I am receiving the following error:

```
Latest version of jq is jq-1.7.1
A different version of jq is installed (jq-1.7); removing it
curl: (3) Illegal characters found in URL

Exited with code exit status 3
```
The pipe was working just fine before that, however I tested with the override:true parameter as well without success.
This is my code:

```
          pre-steps:
            - jq/install:
              version: jq-1.7
              override: true
```

Thank you in advance!
